# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sounds',
                'doc_host': 'https://Ssslakter.github.io',
                'git_url': 'https://github.com/Ssslakter/sounds',
                'lib_path': 'sounds'},
  'syms': {}}
